export const mssqlKeywords = new Set<string>([
  'add',
  'after',
  'all',
  'allocate',
  'alter',
  'analyze',
  'and',
  'ansi_nulls',
  'any',
  'apply',
  'as',
  'asc',
  'assembly',
  'at isolation',
  'at location',
  'authorization',
  'backup',
  'before',
  'begin',
  'begin atomic',
  'begin catch',
  'begin tran',
  'begin transaction',
  'begin try',
  'begin work',
  'between',
  'break',
  'by',
  'call',
  'case',
  'case insensitive',
  'case sensitive',
  'catch',
  'certificate',
  'check',
  'checkpoint',
  'close',
  'clustered',
  'collate',
  'column',
  'comment on',
  'commit',
  'commit work',
  'computed',
  'connect',
  'constraint',
  'continue',
  'create',
  'create or alter',
  'create or replace',
  'credential',
  'cross apply',
  'cross join',
  'current',
  'current row',
  'cursor',
  'database',
  'dbcc',
  'dbspace',
  'deallocate',
  'debug',
  'declare',
  'default',
  'definer',
  'delete',
  'deleted',
  'deny',
  'desc',
  'describe',
  'deterministic',
  'disable',
  'disconnect',
  'distinct',
  'do',
  'domain',
  'drop',
  'dynamic result sets',
  'else',
  'elseif',
  'enable',
  'encrypted',
  'end',
  'end catch',
  'end if',
  'end loop',
  'end try',
  'endif',
  'endpoint',
  'escape',
  'event',
  'except',
  'except all',
  'exception',
  'excluding',
  'exec',
  'execute',
  'execute as',
  'execute immediate',
  'exists',
  'exit',
  'explain',
  'external name',
  'fetch',
  'filegroup',
  'first',
  'following',
  'for',
  'for each row',
  'for each statement',
  'for json',
  'for xml',
  'foreign key',
  'from',
  'full join',
  'full outer join',
  'fulltext index',
  'function',
  'global temporary',
  'go',
  'goto',
  'grant',
  'group',
  'group by',
  'handler',
  'having',
  'holdlock',
  'identity',
  'identity_insert',
  'if',
  'in',
  'including',
  'index',
  'inner join',
  'insert',
  'inserted',
  'instead of',
  'intersect',
  'intersect all',
  'into',
  'invalidate',
  'invoker',
  'is',
  'is distinct from',
  'is not',
  'is not distinct from',
  'is not null',
  'is null',
  'isolation',
  'iterate',
  'join',
  'key',
  'language',
  'lateral',
  'leave',
  'left join',
  'left outer join',
  'like',
  'limit',
  'load table',
  'local temporary',
  'lock',
  'login policy',
  'loop',
  'materialized view',
  'merge',
  'message',
  'minus',
  'modify',
  'natural join',
  'new',
  'next',
  'no result set',
  'no wait',
  'nocount',
  'nolock',
  'nonclustered',
  'not',
  'not between',
  'not deterministic',
  'not in',
  'not like',
  'not null',
  'null',
  'nulls first',
  'nulls last',
  'of',
  'off',
  'offset',
  'old',
  'on',
  'on exception resume',
  'only',
  'open',
  'openquery',
  'openrowset',
  'openxml',
  'option',
  'or',
  'or alter',
  'or replace',
  'order',
  'order by',
  'outer apply',
  'output',
  'over',
  'owner',
  'partition',
  'partition by',
  'passthrough',
  'pivot',
  'plan',
  'preceding',
  'prepare',
  'primary key',
  'print',
  'proc',
  'procedure',
  'publication',
  'quoted_identifier',
  'raiserror',
  'range',
  'read',
  'readcommitted',
  'readtext',
  'readuncommitted',
  'recompile',
  'recursive',
  'references',
  'referencing',
  'refresh materialized view',
  'release savepoint',
  'remote',
  'remote server',
  'rename',
  'repeat',
  'repeatableread',
  'replace',
  'resignal',
  'resume',
  'restore',
  'result',
  'return',
  'returns',
  'revoke',
  'right join',
  'right outer join',
  'role',
  'rollback',
  'rollback to savepoint',
  'rollback tran',
  'rollback transaction',
  'rollback work',
  'row',
  'rowcount',
  'rows',
  'rowtype',
  'savepoint',
  'schema',
  'schemabinding',
  'select',
  'select into',
  'sequence',
  'serializable',
  'server',
  'service',
  'set',
  'set hidden',
  'set option',
  'set temporary option',
  'setuser',
  'signal',
  'snapshot',
  'some',
  'sql security',
  'sqlstate',
  'start',
  'start transaction',
  'statistics',
  'stop',
  'subscription',
  'synchronization profile',
  'synchronize',
  'synonym',
  'table',
  'temporary',
  'text index',
  'then',
  'throw',
  'to',
  'top',
  'tran',
  'transaction',
  'trigger',
  'truncate table',
  'try',
  'type',
  'unbounded',
  'unbounded following',
  'unbounded preceding',
  'union',
  'union all',
  'unique index',
  'unknown',
  'unload',
  'unlock',
  'unpivot',
  'until',
  'update',
  'upsert',
  'use',
  'user',
  'using',
  'validate',
  'value',
  'values',
  'variable',
  'view',
  'wait',
  'waitfor',
  'when',
  'where',
  'while',
  'with',
  'with check option',
  'with encryption',
  'with recompile',
  'write',
  'writetext',
  'xact_abort',
  'xml schema collection'
]);
